version: '3'
services:
  eurekaserver:
    image:   coopersoft/cloud-eurekasvr:latest
    #    deploy:
    #      resources:
    #        limits:
    ##          cpus: '0.05'
    #          memory: 360M
    #        reservations:
    ##          cpus: '0.01'
    #          memory: 128M
    ports:
      - "8761:8761"
    environment:
      TZ: Asia/Shanghai
  configserver:
    image: coopersoft/cloud-confsvr:latest
    ports:
      - "8888:8888"
    environment:
      EUREKASERVER_PORT: 8761
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      ENCRYPT_KEY:       "IMSYMMETRIC"
      TZ: Asia/Shanghai
    links:
      - eurekaserver:eurekaserver
    depends_on:
      - eurekaserver
  zuulserver:
    image: coopersoft/cloud-zuulsvr:latest
    #    deploy:
    #      resources:
    #        limits:
    #          #          cpus: '0.05'
    #          memory: 360M
    #        reservations:
    #          #          cpus: '0.01'
    #          memory: 128M
    ports:
      - "5555:5555"
    environment:
      PROFILE: "default"
      SERVER_PORT: "5555"
      CONFIGSERVER_PORT: 8888
      EUREKASERVER_PORT: 8761
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      TZ: Asia/Shanghai
    links:
      - eurekaserver:eurekaserver
      - configserver:configserver
    depends_on:
      - eurekaserver
      - configserver
  database:
    image: coopersoft/mariadb-min:v1
    #      command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    ports:
      - "3306:3306"
    volumes:
      - "/home/docker/data/db:/var/lib/mysql"
    environment:
      #      - MYSQL_ROOT_PASSWORD=p0stgr@s
      #      - MYSQL_DATABASE=archives
      MYSQL_DATABASE: archives
      MYSQL_ROOT_PASSWORD: p0stgr@s
      #      MYSQL_ROOT_HOST: '%'
      TZ: Asia/Shanghai
  #        - MYSQL_USER=testuser
  #        - MYSQL_PASSWORD=testpassword


  #        docker run --name mariadb_test -e MYSQL_ROOT_PASSWORD=my-secret=pw -d
  #        docker run -d --name mariadb_volume -P -v /data/Db/mariadb:/var/lib/mysql mariadb
  #          nosse4  stable4

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"

  kafkaserver:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafkaserver
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CREATE_TOPICS=dresses:1:1,ratings:1:1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper


  authenticationservice:
    image: coopersoft/cloud-authentication-service:latest
      #deploy:
      #resources:
      #limits:
      #          cpus: '0.05'
      #memory: 360M
      #reservations:
      #          cpus: '0.01'
    #memory: 128M
    ports:
      - "8901:8901"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8901"
      DATABASE_PORT:     3306
      CONFIGSERVER_PORT: 8888
      EUREKASERVER_PORT: 8761
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      ENCRYPT_KEY:       "IMSYMMETRIC"
      TZ: Asia/Shanghai
    links:
      - eurekaserver:eurekaserver
      - database:database
      - configserver:configserver
    depends_on:
      - eurekaserver
      - database
      - configserver

  # ==================  archive app ===================================================

  moneyaccountservice:
    image: coopersoft/construct-attach-corp-service:snapshot
    #    deploy:
    #      resources:
    #        limits:
    #          #          cpus: '0.05'
    #          memory: 360M
    #        reservations:
    #          #          cpus: '0.01'
    #          memory: 128M

    expose:
      - "19001"
    environment:
      PROFILE: "default"
      SERVER_PORT: "19001"
      DATABASE_PORT:     3306
      CONFIGSERVER_PORT: 8888
      EUREKASERVER_PORT: 8761
      AUTHSERVER_PORT:   8091
      KAFKASERVER_PORT:  2181
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      AUTHSERVER_URI:   "http://authenticationservice:8901/auth/user"
      TZ: Asia/Shanghai
    links:
      - eurekaserver:eurekaserver
      - database:database
      - configserver:configserver
      - kafkaserver:kafkaserver
      - zookeeper:zookeeper
    depends_on:
      - eurekaserver
      - database
      - configserver
      - kafkaserver
      - zookeeper


