security:
  oauth2:
    resource:
      userInfoUri: http://192.168.1.21:8901/auth/user

#Setting the logging levels for the service
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    cc.coopersoft: DEBUG


eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://192.168.1.21:8761/eureka/

spring:
  cloud:
    stream:
      rocketmq:
        binder:
          name-server:
            192.168.1.21:9876
      bindings:
        output:
          destination: projectChangeTopic
          content-type: application/json

signing:
  key: "345345fsdfsf5345"
