
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000

#开启actuator管理api
management:
  endpoints:
    web:
      exposure:
        include: '*'


spring:
  redis:
    database: 1  # Redis数据库索引（默认为0）
    host: redis
    port: 6379
    password: p0stgr@s
    jedis:
      pool:
        max-active: 8  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8  # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 0 # 连接超时时间（毫秒）
  security:
    oauth2:
      client:
        registration:
          master-trust-cer:
            provider: keycloak
            client-id: extends
            client-secret: c8f7d947-b83c-4adf-bff8-93b1a49ba2a2
            authorization-grant-type: client_credentials
            scope: Trust
        provider:
          keycloak:
            authorization-uri: http://keycloak:8080/auth/realms/construction/protocol/openid-connect/auth
            token-uri: http://keycloak:8080/auth/realms/construction/protocol/openid-connect/token
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/auth/realms/trust/protocol/openid-connect/certs
  cloud:
    stream:
      rocketmq:
        binder:
          name-server:
            rmqnamesrv:9876
      bindings:
        input:
          destination: trustUserTopic
          content-type: application/json
          group: trustGateway
    loadbalancer:
      ribbon:
        enabled: false
    consul:
      discovery:
        serviceName: ${spring.application.name}
        # 启用服务发现
        enabled: true
        # 启用服务注册
        register: true
        # 服务停止时取消注册
        deregister: true
        # 表示注册时使用IP而不是hostname
        prefer-ip-address: true
        # 执行监控检查的频率
        health-check-interval: 30s
        # 设置健康检查失败多长时间后，取消注册
        health-check-critical-timeout: 30s
        # 健康检查的路径
        health-check-path: /actuator/info
        # 服务注册标识，格式为：应用名称+服务器IP+端口
        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowCredentials: true
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
            - GET
            - POST
            - DELETE
            - PUT
            - OPTION
